name: Metrics for Profile
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering
permissions:
  contents: write  # Grants write access for committing SVGs
jobs:
  full-year-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
  calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Generate full-year ISO calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: dimuthu638
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
  organization:
    runs-on: ubuntu-latest
    steps:
      - name: Organization introduction
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: github
          base: header
          plugin_introduction: yes
